# Generated by Django 2.0.3 on 2018-08-09 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longtitude', models.FloatField()),
                ('LocationName', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('SerialNumber', models.CharField(max_length=1000)),
                ('Fee', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Birthday', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('Wage', models.DecimalField(decimal_places=6, max_digits=10)),
                ('IsActive', models.BooleanField()),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nespressoAPI.Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('IsActive', models.BooleanField()),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nespressoAPI.Locations')),
            ],
        ),
    ]
