# Generated by Django 2.0.3 on 2018-08-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nespressoAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personnels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Birthday', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('Wage', models.DecimalField(decimal_places=6, max_digits=10)),
                ('IsActive', models.BooleanField()),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nespressoAPI.Locations')),
            ],
            options={
                'db_table': 'Personnels',
            },
        ),
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('IsActive', models.BooleanField()),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nespressoAPI.Locations')),
            ],
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='Location',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
