# Generated by Django 2.0.3 on 2018-08-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nespressoAPI', '0002_auto_20180809_2051'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locations',
            table='Locations',
        ),
        migrations.AlterModelTable(
            name='machines',
            table='Machines',
        ),
        migrations.AlterModelTable(
            name='managers',
            table='Managers',
        ),
        migrations.AlterModelTable(
            name='supervisors',
            table='Supervisors',
        ),
    ]
