# Generated by Django 2.0.3 on 2018-08-09 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nespressoAPI', '0003_auto_20180809_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(max_length=1000)),
                ('CustomerName', models.CharField(max_length=200)),
                ('CustomerSurname', models.CharField(max_length=200)),
                ('CustomerPhoneNumber', models.CharField(max_length=30)),
                ('CustomerEmail', models.EmailField(max_length=200)),
                ('IsCampaign', models.BooleanField()),
            ],
            options={
                'db_table': 'Sales',
            },
        ),
        migrations.AlterField(
            model_name='machines',
            name='Fee',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='Machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nespressoAPI.Machines'),
        ),
        migrations.AddField(
            model_name='sales',
            name='Personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nespressoAPI.Personnels'),
        ),
    ]
